export const COUNTRIES = [
  {
    name: "Poland",
    code: "PL",
    language: "pl",
    icon: "poland.svg",
  },
  {
    name: "United States",
    code: "US",
    language: "en",
    icon: "united-states.svg",
  },
  {
    name: "United Kingdom",
    code: "GB",
    language: "en",
    icon: "united-kingdom.svg",
  },
  {
    name: "Ukraine",
    code: "UA",
    language: "uk",
    icon: "ukraine.svg",
  },
  {
    name: "Spain",
    code: "ES",
    language: "es",
    icon: "spain.svg",
  },
  {
    name: "Sweden",
    code: "SE",
    language: "sv",
    icon: "sweden.svg",
  },
  {
    name: "Canada",
    code: "CA",
    language: "en",
    icon: "canada.svg",
  },
  {
    name: "Austria",
    code: "AT",
    language: "de",
    icon: "austria.svg",
  },
  {
    name: "Belgium",
    code: "BE",
    language: "nl",
    icon: "belgium.svg",
  },
  {
    name: "Bulgaria",
    code: "BG",
    language: "bg",
    icon: "bulgaria.svg",
  },
  {
    name: "Croatia",
    code: "HR",
    language: "hr",
    icon: "croatia.svg",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    language: "cs",
    icon: "czech-republic.svg",
  },
  {
    name: "Denmark",
    code: "DK",
    language: "da",
    icon: "denmark.svg",
  },
  {
    name: "Estonia",
    code: "EE",
    language: "et",
    icon: "estonia.svg",
  },
  {
    name: "Finland",
    code: "FI",
    language: "fi",
    icon: "finland.svg",
  },
  {
    name: "France",
    code: "FR",
    language: "fr",
    icon: "france.svg",
  },
  {
    name: "Germany",
    code: "DE",
    language: "de",
    icon: "germany.svg",
  },
  {
    name: "Greece",
    code: "GR",
    language: "el",
    icon: "greece.svg",
  },
  {
    name: "Hungary",
    code: "HU",
    language: "hu",
    icon: "hungary.svg",
  },
  {
    name: "Iceland",
    code: "IS",
    language: "is",
    icon: "iceland.svg",
  },
  {
    name: "Ireland",
    code: "IE",
    language: "en",
    icon: "ireland.svg",
  },
  {
    name: "Italy",
    code: "IT",
    language: "it",
    icon: "italy.svg",
  },
  {
    name: "Netherlands",
    code: "NL",
    language: "nl",
    icon: "netherlands.svg",
  },
  {
    name: "Norway",
    code: "NO",
    language: "no",
    icon: "norway.svg",
  },
  {
    name: "Portugal",
    code: "PT",
    language: "pt",
    icon: "portugal.svg",
  },
  {
    name: "Romania",
    code: "RO",
    language: "ro",
    icon: "romania.svg",
  },
  {
    name: "Slovakia",
    code: "SK",
    language: "sk",
    icon: "slovakia.svg",
  },
  {
    name: "Slovenia",
    code: "SI",
    language: "sl",
    icon: "slovenia.svg",
  },
] as const
